services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=pettracker
    ports:
      - "5433:5432" # mapeie a porta 5433 do host para a porta 5432 do contêiner
